# Generated by Django 4.2.1 on 2023-12-20 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='ficha_tecnica',
            field=models.TextField(blank=True, null=True),
        ),
    ]
